### ISSUE TITLE
Including animations directly in FR.json file

### ISSUE THREAD

**Issue by GiAnMMV** [Nadekooo/YTTDFR#29]
Wouldn't it better to include thr animations in the FR.json file instead of patching the Animations.json file, which could change in future updates? I tested it and it works if you use as value of "AnimationConvert_X" a string containing the JSON object of the new animation.

**Comment by vinceh121** [comment]
Hi,

While the Animations.json file can change through updates of the game, so will the keys of the FR.json file. Conflict through updates is a problem that can't be avoided, and we better be prepared to face it. That's why I preferred going with jsondiffpatch. I might've been more inclined to avoid modifying other files than FR.json if it was the only file that needed to be patched in order to support the language, but that's not the case. See the concerned files in the workflow:
https://github.com/Nadekooo/YTTDFR/blob/85086eec4923218875dfb0dc619f416f090641c3/.github/workflows/Build-YttdFr.yml#L38

Moreover, serializing JSON inside a JSON string is a bad pattern.
